language: node_js
os: 'linux'

node_js:
  - 16

install:
  - npm install
  - npm run build

script:
  - npm run test

deploy:
  - provider: s3
    upload-dir: $TRAVIS_BRANCH
    skip_cleanup: true
    local_dir: ./dist
